# Generated by Django 2.2.3 on 2021-05-08 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(blank=True, max_length=300, null=True)),
                ('value', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StringValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(blank=True, max_length=300, null=True)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Variable')),
            ],
        ),
        migrations.CreateModel(
            name='BooleanValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.BooleanField(default=True)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Variable')),
            ],
        ),
    ]
